//
// Singleton.cs
//
 
namespace Common
{

  //
  // Adapted from the code generated by Windows Template Studio
  //

  //
  // Ha, this implementation is now reckoned to be flawed - see 
  // release notes for latest v7.9 of Windows Community Toolkit !!!
  //

  public static class Singleton_OLD_DO_NOT_USE<T> where T : new()
  {

    private static readonly System.Collections.Concurrent.ConcurrentDictionary<System.Type,T> g_instances = new() ;

    public static T Instance => g_instances.GetOrAdd(
      typeof(T), 
      (t) => new T()
    ) ;

  }

}
