//
// Singleton.cs
//
 
namespace Common
{

  //
  // Adapted from the code generated by Windows Template Studio
  //

  public static class Singleton<T> where T : new()
  {

    private static System.Collections.Concurrent.ConcurrentDictionary<System.Type,T> g_instances = new() ;

    public static T Instance => g_instances.GetOrAdd(
      typeof(T), 
      (t) => new T()
    ) ;

  }

}
