//
// Json.cs
//

using System.Threading.Tasks ;

namespace Common
{

  //
  // Adapted from the code generated by Windows Template Studio
  //

  public static class Json
  {

    public static T ToObject<T> ( string value )
    => Newtonsoft.Json.JsonConvert.DeserializeObject<T>(value) ;

    public static string Stringify ( object value )
    => Newtonsoft.Json.JsonConvert.SerializeObject(value) ;

    public static async Task<T> ToObjectAsync<T> ( string value )
    {
      return await Task.Run<T>(
        () => Newtonsoft.Json.JsonConvert.DeserializeObject<T>(value)
      ) ;
    }

    public static async Task<string> StringifyAsync ( object value )
    {
      return await Task.Run<string>(
        () => Newtonsoft.Json.JsonConvert.SerializeObject(value)
      ) ;
    }

  }

}
